=begin
#Svea Checkout API

#Svea Checkout API

OpenAPI spec version: v1
Contact: support-webpay@sveaekonomi.se
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'

# Unit tests for SveaCheckout::UtilApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UtilApi' do
  before do
    # run before each test
    @instance = SveaCheckout::UtilApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UtilApi' do
    it 'should create an instance of UtilApi' do
      expect(@instance).to be_instance_of(SveaCheckout::UtilApi)
    end
  end

  # unit tests for util_get_available_part_payment_campaigns
  # This request returns a list of available B2C/B2B part payment campaigns.
  # HTTP status code 200 indicates success, everything else indicates a failure.
  # @param is_company True for B2B, false for B2C
  # @param [Hash] opts the optional parameters
  # @return [Array<CampaignCodeInfo>]
  describe 'util_get_available_part_payment_campaigns test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
