=begin
#Svea Checkout API

#Svea Checkout API

OpenAPI spec version: v1
Contact: support-webpay@sveaekonomi.se
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'date'

module SveaCheckout
  # @@include(\"minor-currency.md\")
  class OrderRow
    # Articlenumber as a string, can contain letters and numbers.
    attr_accessor :article_number

    # Article name.
    attr_accessor :name

    # Quantity of the product.  1-9 digits.
    attr_accessor :quantity

    # Price of the product including VAT.  1-13 digits, can be negative.
    attr_accessor :unit_price

    # The discountpercent of the product.    *Examples:*    <list type=\"none\"><item>0-10000. No fractions.</item><item>0 = 0%</item><item>100 = 1%</item><item>1000 = 10%</item><item>9900 = 99%</item><item>10000 = 100%</item></list>
    attr_accessor :discount_percent

    # The VAT percentage of the current product.  Valid vat percentage for that country.
    attr_accessor :vat_percent

    # The unit type, e.g., “st”, “pc”, “kg” etc.
    attr_accessor :unit

    # Can be used when creating or updating an order.   The returned rows will have their corresponding temporaryreference as they were given in the indata.   It will not be stored and will not be returned in GetOrder.
    attr_accessor :temporary_reference

    # The row number the row will have in the Webpay system
    attr_accessor :row_number

    # Metadata visible to the store
    attr_accessor :merchant_data

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'article_number' => :'ArticleNumber',
        :'name' => :'Name',
        :'quantity' => :'Quantity',
        :'unit_price' => :'UnitPrice',
        :'discount_percent' => :'DiscountPercent',
        :'vat_percent' => :'VatPercent',
        :'unit' => :'Unit',
        :'temporary_reference' => :'TemporaryReference',
        :'row_number' => :'RowNumber',
        :'merchant_data' => :'MerchantData'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'article_number' => :'String',
        :'name' => :'String',
        :'quantity' => :'Integer',
        :'unit_price' => :'Integer',
        :'discount_percent' => :'Integer',
        :'vat_percent' => :'Integer',
        :'unit' => :'String',
        :'temporary_reference' => :'String',
        :'row_number' => :'Integer',
        :'merchant_data' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'ArticleNumber')
        self.article_number = attributes[:'ArticleNumber']
      end

      if attributes.has_key?(:'Name')
        self.name = attributes[:'Name']
      end

      if attributes.has_key?(:'Quantity')
        self.quantity = attributes[:'Quantity']
      end

      if attributes.has_key?(:'UnitPrice')
        self.unit_price = attributes[:'UnitPrice']
      end

      if attributes.has_key?(:'DiscountPercent')
        self.discount_percent = attributes[:'DiscountPercent']
      end

      if attributes.has_key?(:'VatPercent')
        self.vat_percent = attributes[:'VatPercent']
      end

      if attributes.has_key?(:'Unit')
        self.unit = attributes[:'Unit']
      end

      if attributes.has_key?(:'TemporaryReference')
        self.temporary_reference = attributes[:'TemporaryReference']
      end

      if attributes.has_key?(:'RowNumber')
        self.row_number = attributes[:'RowNumber']
      end

      if attributes.has_key?(:'MerchantData')
        self.merchant_data = attributes[:'MerchantData']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @quantity.nil?
        invalid_properties.push('invalid value for "quantity", quantity cannot be nil.')
      end

      if @unit_price.nil?
        invalid_properties.push('invalid value for "unit_price", unit_price cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @quantity.nil?
      return false if @unit_price.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          article_number == o.article_number &&
          name == o.name &&
          quantity == o.quantity &&
          unit_price == o.unit_price &&
          discount_percent == o.discount_percent &&
          vat_percent == o.vat_percent &&
          unit == o.unit &&
          temporary_reference == o.temporary_reference &&
          row_number == o.row_number &&
          merchant_data == o.merchant_data
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [article_number, name, quantity, unit_price, discount_percent, vat_percent, unit, temporary_reference, row_number, merchant_data].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SveaCheckout.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
